source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/onnxruntime-1.27.0.jar
javacDefaultEncoding.. = UTF-8
